accounts/urls.py
from importlib import import_module

from django.urls import path

from allauth.socialaccount import providers

from . import views

# URL шаблоны, связывают URL с отображеними
urlpatterns = [
    path('login/', views.login_view, name='login'),
]

# Добавляет URL провайдеров
provider_urlpatterns = []
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        provider_urlpatterns += prov_urlpatterns
urlpatterns += provider_urlpatterns

entries/urls.py
from django.urls import path

from . import views

# URL шаблоны, связывают URL с отображеними
urlpatterns = [
    path('', views.index_view, name="index"),
    path('create/', views.create_view, name='create'),
    path('edit/<int:pk>/', views.change_view, name='edit'),
    path('delete/<int:pk>/', views.delete_view, name='delete'),
    path('search/', views.search_view, name='search'),
]

notebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# URL шаблоны, связывают URL с отображеними
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('entries/', include('entries.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

entries/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth import get_user_model

from phonenumber_field.modelfields import PhoneNumberField


# Модель записи (представляет таблицу в БД)
class EntryModel(models.Model):
    RANDOM = 'RD'
    EMPLOYEE = 'EP'
    CLIENT = 'CL'
    PARTNER = 'PT'
    STATUS_CHOICES = [
        (RANDOM, 'Random'),
        (EMPLOYEE, 'Employee'),
        (CLIENT, 'Client'),
        (PARTNER, 'Partner')
    ]
    owner = models.ForeignKey(get_user_model(),
                              related_name='entries',
                              on_delete=models.CASCADE,
                              blank=False,
                              null=False)
    name = models.CharField(max_length=50, blank=False, null=False)
    phone_number = PhoneNumberField(blank=False, null=False)
    address = models.CharField(max_length=100, blank=True, null=True)
    status = models.CharField(max_length=2,
                              choices=STATUS_CHOICES,
                              default=RANDOM)
    comment = models.TextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="entries/%Y/%m/%d/")

    def __str__(self):
        return f'{self.name}: {self.phone_number}'

entries/forms.py
from django import forms
from .models import EntryModel


# Добоаляет форму для модели Entry
class EntryForm(forms.ModelForm):
    class Meta:
        model = EntryModel
        fields = ['name', 'phone_number', 'address', 'status', 'comment', 'address', 'image']
    

accounts/views.py
from django.shortcuts import render

# Авторизация через провайдеров
def login_view(request):
    return render(request, 'accounts/login.html', {})

entries/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET
from django.contrib.postgres.search import SearchVector

from .forms import EntryForm
from .models import EntryModel


# Отображение главной страницы со всеми записями
# Получает все записи текущего пользователя, и после
# передает их в шаблон для отображения
@login_required
def index_view(request):
    status = request.GET.get('status', '')
    entries = EntryModel.objects.filter(owner=request.user)
    if status:
        entries = entries.filter(status=status)
    return render(request, 'entries/index.html', {'entries': entries})

# Отображение создания записи
# В зависимости от метода запроса отправляет пустую форму
# для заполнения, либо сохраняет данные формы в БД
@login_required
def create_view(request):
    if request.method == 'POST':
        entry_form = EntryForm(request.POST, request.FILES)
        if entry_form.is_valid():
            entry = entry_form.save(commit=False)
            entry.owner = request.user
            entry.save()
            return redirect('index')
    else:
        entry_form = EntryForm()
    return render(request, 'entries/create.html', {'entry_form': entry_form})

# Отображение изменения записи
# В зависимости от метода запроса отправляет форму
# с заполненными старыми данными, либо сохраняет новые
# данные в БД
@login_required
def change_view(request, pk):
    entry = get_object_or_404(EntryModel, pk=pk)
    if request.method == 'POST':
        entry_form = EntryForm(request.POST, request.FILES, instance=entry)
        if entry_form.is_valid():
            entry_form.save()
            return redirect('index')
    else:
        entry_form = EntryForm(instance=entry)
    return render(request, 'entries/create.html', {'entry_form': entry_form,
                                                   'entry': entry})

# Удаление записи по индификатору
@login_required
def delete_view(request, pk):
    entry = get_object_or_404(EntryModel, pk=pk)
    entry.delete()
    return redirect('index')

# Поиск записей
# Группирует столбцы указанные в SearchVector
# и осуществляе поиск по словам из query
@login_required
@require_GET
def search_view(request):
    query = request.GET.get('query', '')
    if query:
        entries = EntryModel.objects.annotate(
                        search=SearchVector('name', 'phone_number', 'address', 'comment')
                ).filter(search=query, owner=request.user).all()
    else:
        return redirect('index')
    return render(request, 'entries/index.html', {'entries': entries})

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load socialaccount %}

{% block title %}login{% endblock %}

{% block content %}
    <div id="content">
        <h1>Login page</h1> 
    <section>
        <ul class="list-socials">
            <li class="list-item-soical">
                <a href="{% provider_login_url 'google' process='login' %}" class='btn'>Login with Google</a>
            </li>
            <li class="list-item-soical">
                <a href="{% provider_login_url 'vk' process='login' %}" class='btn'>Login with VK</a>
            </li>
        </ul>
    </section>
{% endblock %}

entries/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

entries/templates/entries/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% if entry %}change{% else %}create{% endif %}{% endblock %}

{% block content %}
    <section>
        <ul>
            <li><a href="{% url 'index' %}" class='btn'>Вернуться к списку</a></li>
            {% if entry %}<li><a href="{% url 'delete' entry.pk %}" class='btn'>Удалить</a></li>{% endif %}
        </ul>
    </section> 
    <section id='section-image'>
        <img src="{% if entry.image %}{{ entry.image.url }}{% else %}{% static 'entries/default_image.png' %}{% endif %}" alt="">
    </section>

    <section id='change-form'>
        <form action="{% if entry %}{% url 'edit' entry.pk %}{% else %}{% url 'create' %}{% endif %}" method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_name">Имя:</label> 
            <input type="text" name="name" value="{% if entry %}{{ entry.name }}{% endif %}" maxlength="50" required="" id="id_name">
            <label for="id_phone_number">Номер телефона:</label>
            <input type="tel" name="phone_number" value="{% if entry %}{{ entry.phone_number }}{% endif %}" maxlength="128" required="" id="id_phone_number">
            <label for="id_address">Адрес:</label> 
            <input type="text" name="address" value="{% if entry and entry.address %}{{ entry.address }}{% endif %}" maxlength="100" id="id_address">
            <p>
                <label for="id_status">Статус:</label>
                <select name="status" id="id_status">
                    <option value="RD" {% if entry.status == "RD" %}selected{% endif %}>По умолчанию</option>
                    <option value="EP" {% if entry.status == "EP" %}selected{% endif %}>Сотрудник</option>
                    <option value="CL" {% if entry.status == "CL" %}selected{% endif %}>Клиент</option>
                    <option value="PT" {% if entry.status == "PT" %}selected{% endif %}>Бизнес-партнер</option>
                </select>
            </p>
            <label for="id_comment">Коментарий:</label> 
            <textarea name="comment" cols="40" rows="5" id="id_comment">{% if entry %}{{ entry.comment }}{% endif %}</textarea>
            <p><label for="id_image">Избражение:</label>
            <input type="file" name="image" accept="image/*" id="id_image"></p>
            <button type="submit">{% if entry %}Изменить{% else %}Создать{% endif %}</button>
        </form>
    </section>
{% endblock %}

entries/templates/entries/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}index{% endblock %}

{% block content %}
<h1>Записная книжка</h1>
        <section id="section-form">
            <form action="{% url 'search' %}" method="GET">
                <input type="text" name='query'>
                <button type="submit">Поиск</button>
            </form>
        </section>        

        <section>
            <ul>
                <li><a href="{% url 'login' %}" class="btn">Сменить аккаунт</a></li>
                <li><a href="{% url 'create' %}" class="btn">Создать запись</a></li>
            </ul>
            <br><br>
            <ul>
                <li><a href="{% url 'index' %}?status=EP" class="btn" style="color:crimson">Сотрудники</a></li>
                <li><a href="{% url 'index' %}?status=CL" class="btn" style="color:teal">Клиенты</a></li>
                <li><a href="{% url 'index' %}?status=PT" class="btn" style="color:green">Партнеры</a></li>
                <li><a href="{% url 'index' %}" class="btn">Все</a></li>
            </ul>
        </section>
        <section>
            {% if entries %}
                <table>
                    <thead>
                        <tr>
                            <th></th>
                            <th>Имя</th>
                            <th>Номер телефона</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for entry in entries %}
                            <tr>
                                <td><img src="{% if entry.image %}{{ entry.image.url }}{% else %}{% static 'entries/default_image.png' %}{% endif %}" alt="" class="img-icon"></td>
                                <td><a href="{% url 'edit' entry.pk %}" class='btn'>{{ entry.name }}</a>
                                    {% if entry.status == "EP" %}<br><i style="color:crimson">Сотрудник</i>
                                    {% elif entry.status == "CL" %}<br><i style="color:teal">Клиент</i>
                                    {% elif entry.status == "PT" %}<br><i style="color:green">Бизнес-партнер</i>{% endif %}
                                </td>
                                <td>{{ entry.phone_number }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h2>Нет записей...</h2>
            {% endif %}
        </section>
{% endblock %}